language: php
php:
  - '5.4' # Only some of the tests will run for this version, as we support PHP >= 7.0
  - '7.0'
  - '7.1'
dist: trusty
sudo: required # this seems to be required for some reason to get MySQL to work
services:
  - mysql
cache:
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb'
  - mysql -e "GRANT ALL ON testdb.* TO 'travis'@'localhost'"
  - npm install -g gulp-cli
  - npm install
before_script:
  - composer install
script:
  - ./test/test_for_syntax_errors.sh
  - ./test/test_installation.sh
  - ./test/test_phpcs.sh
  #- find dt-assets/ -iname "*.min.js" -or -iname "*.map" -or -iname "*.min.css" -delete && rm -rf build/
  #- gulp
  #- git diff --exit-code
  # If the previous command returns a non-zero exit code, that means gulp has
  # modified some files in version control. This shouldn't happen, developers
  # should remember to run gulp before committing.