name: Release

on:
  push:
    tags:
    - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    # cp -r * disciple-tools-webform.php admin metrics network post-type includes languages spinner.svg version-control.json LICENSE SECURITY.md disciple-tools-webform/ |
    # Build the plugin zip and publish it as the asset of a GitHub release for the pushed tag
    - name: Build project
      run: |
        mkdir disciple-tools-webform
        cp -r disciple-tools-webform.php dt-mapping includes languages magic-link public spinner.svg version-control.json LICENSE SECURITY.md disciple-tools-webform/
        zip -r disciple-tools-webform.zip disciple-tools-webform
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "$GITHUB_REF_NAME" disciple-tools-webform.zip --title "Release $GITHUB_REF_NAME" --notes ""
